export const CONTENT = {
  es: {
    nav: [
      { label: 'Resumen', href: '#top' },
      { label: 'Capacidades', href: '#services' },
      { label: 'Estudio del Asistente', href: '#studio' },
      { label: 'Bodega', href: '#bodega' },
      { label: 'Configuración', href: '#setup' },
    ],
    hero: {
      eyebrow: 'ASISTENTE PERSONAL DE FADI',
      headline: 'Una sola base para vida, trabajo y entrenamiento.',
      tagline: 'Precisión ejecutiva. Cuidado concierge. Disciplina fitness.',
      description:
        'Organiza prioridades, diseña itinerarios y entrena con planes reales listos para ejecutar.\nHecho para el ritmo de Fadi, con rutinas, comidas y comunicación siempre alineadas a sus metas.',
      cta: 'Iniciar configuración',
      ctaSecondary: 'Ver capacidades',
      metrics: [
        { value: '24/7', label: 'Soporte inmediato' },
        { value: '7 días', label: 'Planes de entrenamiento' },
        { value: '5 min', label: 'Outputs listos' },
      ],
    },
    services: {
      title: 'Diseñado para la vida de Fadi',
      subtitle:
        'Operaciones ejecutivas, concierge de alto nivel y coaching fitness en un mismo panel.',
      items: [
        {
          title: 'Centro Ejecutivo',
          desc: 'Agenda diaria, prioridades y seguimiento sin fricción.',
          detailedDesc:
            'Convierte tareas en bloques de tiempo, prepara reuniones y crea listas de seguimiento accionables.',
          features: ['Bloques de tiempo inteligentes', 'Briefs de reunión', 'Recordatorios de follow-up'],
        },
        {
          title: 'Concierge & Lifestyle',
          desc: 'Reservas, viajes y experiencias curadas a medida.',
          detailedDesc:
            'Diseña itinerarios con ritmo realista, recomendaciones locales y checklist de reservas.',
          features: ['Itinerarios por momento del día', 'Checklist de reservas', 'Preferencias personalizadas'],
        },
        {
          title: 'Entrenador Personal',
          desc: 'Rutinas de gimnasio con progresión y enfoque en objetivos.',
          detailedDesc:
            'Programas semanales con división de músculos, volumen y recuperación para avanzar sin estancarse.',
          features: ['Splits por objetivo', 'Cues de técnica', 'Recuperación guiada'],
        },
        {
          title: 'Nutrición & Meal Prep',
          desc: 'Planes de comida alineados a energía y resultados.',
          detailedDesc:
            'Menús diarios con macros sugeridas, hidratación y estrategia de preparación.',
          features: ['Macros por meta', 'Ideas de batch cooking', 'Hidratación diaria'],
        },
        {
          title: 'Comunicación & Conocimiento',
          desc: 'Emails, análisis de documentos y chat en un mismo flujo.',
          detailedDesc:
            'Redacta correos claros, resume documentos y responde consultas con contexto.',
          features: ['Drafts de email', 'Resumen + acciones', 'Chat contextual'],
        },
      ],
      stackTitle: 'Módulos clave',
      stack: ['Planificación diaria', 'Concierge', 'Entrenamiento', 'Nutrición', 'Email', 'Documentos', 'Chat'],
    },
    generator: {
      title: 'Estudio del Asistente',
      subtitle:
        'Genera planes reales, correos listos y análisis de documentos en segundos.',
      executive: {
        title: 'Planificador Ejecutivo',
        description: 'Transforma tareas en una agenda con tiempos reales.',
        labels: {
          tasks: 'Tareas y prioridades',
          focus: 'Enfoque del día',
          startTime: 'Inicio',
          endTime: 'Cierre',
        },
        cta: 'Crear agenda',
        outputTitle: 'Agenda sugerida',
      },
      concierge: {
        title: 'Concierge & Itinerario',
        description: 'Construye un día perfecto con ritmo y reservas.',
        labels: {
          city: 'Ciudad base',
          date: 'Fecha',
          preferences: 'Preferencias',
          pace: 'Ritmo del día',
        },
        cta: 'Crear itinerario',
        outputTitle: 'Plan del día',
      },
      fitness: {
        title: 'Entrenamiento + Comidas',
        description: 'Rutinas y meal plan ajustados a la meta de Fadi.',
        labels: {
          goal: 'Meta principal',
          days: 'Días por semana',
          equipment: 'Equipamiento',
          experience: 'Nivel',
          diet: 'Estilo de alimentación',
        },
        cta: 'Generar plan fitness',
        outputTitle: 'Plan semanal',
      },
      email: {
        title: 'Escritor de Email',
        description: 'Correos listos para enviar con tono exacto.',
        labels: {
          recipient: 'Destinatario',
          purpose: 'Objetivo del correo',
          tone: 'Tono',
          points: 'Puntos clave',
        },
        cta: 'Crear email',
        outputTitle: 'Borrador listo',
      },
      analyzer: {
        title: 'Analizador de Documentos',
        description: 'Resumen, acciones y preguntas clave en un vistazo.',
        labels: {
          document: 'Pega el documento aquí',
        },
        cta: 'Analizar documento',
        outputTitle: 'Resumen ejecutivo',
      },
      chat: {
        title: 'Chat del Asistente',
        description: 'Respuestas rápidas con contexto de Fadi.',
        labels: {
          message: 'Escribe un mensaje',
          hint: 'Ejemplo: prepara un plan para mañana con enfoque en reuniones y entrenamiento.',
        },
        cta: 'Enviar',
      },
    },
    contact: {
      title: 'Configura el asistente de Fadi',
      subtitle:
        'Cuéntanos cómo trabaja Fadi y el asistente generará un brief con prioridades y próximos pasos.',
      highlights: [
        'Agenda diaria + prioridades',
        'Metas de entrenamiento + equipamiento',
        'Preferencias de alimentación',
        'Ciudad base + viajes frecuentes',
      ],
      form: {
        name: 'Nombre',
        focus: 'Enfoque semanal',
        trainingGoal: 'Objetivo fitness',
        dietaryStyle: 'Preferencias de alimentación',
        homeCity: 'Ciudad base',
        submit: 'Generar brief',
      },
      result: {
        title: 'Brief del asistente',
        nextStepsTitle: 'Siguientes acciones recomendadas',
      },
    },
    bodega: {
      title: 'Control de Bodega',
      subtitle: 'Sistema de inventario para restaurantes en Chile. Controla stock, vencimientos y mermas en tiempo real.',
      eyebrow: 'Prevención de Pérdidas',
      views: {
        dashboard: 'Panel',
        productos: 'Productos',
        movimientos: 'Movimientos',
        vencimientos: 'Vencimientos',
        mermas: 'Mermas',
        reportes: 'Reportes',
      },
      dashboard: {
        totalProducts: 'Productos registrados',
        totalValue: 'Valor total inventario',
        activeAlerts: 'Alertas activas',
        monthlyLoss: 'Merma del mes',
        lossTarget: 'Meta: bajo 2% del inventario',
        nearExpiry: 'Próximos a vencer (7 días)',
        lowStock: 'Bajo stock mínimo',
        recentMovements: 'Últimos movimientos',
        lossBreakdown: 'Mermas por categoría',
        currency: 'CLP',
      },
      products: {
        addProduct: 'Agregar producto',
        name: 'Nombre',
        sku: 'SKU',
        category: 'Categoría',
        unit: 'Unidad',
        zone: 'Zona almacenamiento',
        minStock: 'Stock mínimo',
        maxStock: 'Stock máximo',
        currentStock: 'Stock actual',
        cost: 'Costo unitario (CLP)',
        supplier: 'Proveedor',
        shelfLife: 'Vida útil (días)',
        save: 'Guardar',
        cancel: 'Cancelar',
        search: 'Buscar producto...',
      },
      movements: {
        addMovement: 'Registrar movimiento',
        product: 'Producto',
        type: 'Tipo',
        quantity: 'Cantidad',
        responsable: 'Responsable',
        notes: 'Notas',
        date: 'Fecha',
        types: {
          entrada: 'Entrada',
          salida: 'Salida',
          ajuste: 'Ajuste',
          merma: 'Merma',
        },
      },
      expiry: {
        title: 'Control de Vencimientos',
        expired: 'Vencidos',
        critical: 'Vence hoy o mañana',
        warning: 'Vence en 7 días',
        ok: 'Vigente',
        daysLeft: 'días restantes',
        lot: 'Lote',
        noExpiry: 'Sin productos próximos a vencer',
      },
      losses: {
        addLoss: 'Registrar merma',
        reason: 'Causa',
        costImpact: 'Impacto en CLP',
        preventable: 'Prevenible',
        yes: 'Sí',
        no: 'No',
        reasons: {
          vencimiento: 'Vencimiento',
          deterioro: 'Deterioro',
          robo: 'Robo/Hurto',
          error_conteo: 'Error de conteo',
          mal_almacenamiento: 'Mal almacenamiento',
          devolucion_proveedor: 'Devolución proveedor',
          otro: 'Otro',
        },
        totalLoss: 'Pérdida total del período',
        preventableRate: 'Tasa prevenible',
      },
      reports: {
        title: 'Reportes y Análisis',
        lossVsInventory: 'Merma vs. Inventario',
        lossByReason: 'Mermas por causa',
        lossByCategory: 'Mermas por categoría',
        stockTurnover: 'Rotación de stock',
        topLosses: 'Productos con más merma',
        recommendations: 'Recomendaciones',
      },
      categories: {
        carnes: 'Carnes',
        pescados: 'Pescados y Mariscos',
        lacteos: 'Lácteos',
        verduras: 'Verduras',
        frutas: 'Frutas',
        abarrotes: 'Abarrotes',
        bebidas: 'Bebidas',
        congelados: 'Congelados',
        condimentos: 'Condimentos',
        limpieza: 'Limpieza',
      },
      zones: {
        refrigerado: 'Refrigerado (0-5°C)',
        congelado: 'Congelado (-18°C)',
        seco: 'Bodega seca',
        ambiente: 'Temperatura ambiente',
      },
      units: ['kg', 'lt', 'unidad', 'caja', 'bolsa', 'botella'],
      alerts: {
        lowStock: 'bajo stock mínimo',
        nearExpiry: 'vence pronto',
        expired: 'vencido',
        highLoss: 'merma alta detectada',
      },
    },
  },
  en: {
    nav: [
      { label: 'Overview', href: '#top' },
      { label: 'Capabilities', href: '#services' },
      { label: 'Assistant Studio', href: '#studio' },
      { label: 'Bodega', href: '#bodega' },
      { label: 'Setup', href: '#setup' },
    ],
    hero: {
      eyebrow: "FADI'S PERSONAL ASSISTANT",
      headline: 'One home for life, work, and training.',
      tagline: 'Executive precision. Concierge care. Trainer discipline.',
      description:
        "Organize priorities, design itineraries, and train with real plans that are ready to execute.\nBuilt for Fadi's pace with routines, meals, and communication aligned to his goals.",
      cta: 'Start the setup',
      ctaSecondary: 'Explore capabilities',
      metrics: [
        { value: '24/7', label: 'Instant support' },
        { value: '7-day', label: 'Training plans' },
        { value: '5 min', label: 'Ready outputs' },
      ],
    },
    services: {
      title: "Built for Fadi's life",
      subtitle:
        'Executive operations, white-glove concierge, and fitness coaching in one workspace.',
      items: [
        {
          title: 'Executive Command Center',
          desc: 'Daily priorities, calendar blocks, and follow-through without friction.',
          detailedDesc:
            'Turns tasks into time blocks, prepares meeting briefs, and creates follow-up checklists.',
          features: ['Smart time blocks', 'Meeting briefing cards', 'Follow-up reminders'],
        },
        {
          title: 'Concierge & Lifestyle',
          desc: 'Reservations, travel, and experiences curated to taste.',
          detailedDesc:
            'Builds realistic itineraries with local recommendations and reservation checklists.',
          features: ['Day-part itineraries', 'Reservation checklist', 'Preference-based picks'],
        },
        {
          title: 'Personal Trainer',
          desc: 'Gym routines with progression and goal-based splits.',
          detailedDesc:
            'Weekly programs with muscle splits, volume guidance, and recovery built in.',
          features: ['Goal-based splits', 'Form cues', 'Recovery guidance'],
        },
        {
          title: 'Nutrition & Meal Prep',
          desc: 'Meal plans aligned to energy, macros, and results.',
          detailedDesc:
            'Daily menus with suggested macros, hydration targets, and prep strategy.',
          features: ['Macro targets', 'Batch cooking ideas', 'Hydration guidance'],
        },
        {
          title: 'Comms & Knowledge',
          desc: 'Emails, document analysis, and chat support in one flow.',
          detailedDesc:
            'Draft clear emails, summarize documents, and answer questions with context.',
          features: ['Email drafts', 'Summaries + action items', 'Context-aware chat'],
        },
      ],
      stackTitle: 'Core modules',
      stack: ['Daily planning', 'Concierge', 'Training', 'Nutrition', 'Email', 'Documents', 'Chat'],
    },
    generator: {
      title: 'Assistant Studio',
      subtitle:
        'Generate real plans, ready-to-send emails, and document analyses in seconds.',
      executive: {
        title: 'Executive Planner',
        description: 'Turn tasks into a timed agenda with focus blocks.',
        labels: {
          tasks: 'Tasks and priorities',
          focus: 'Daily focus',
          startTime: 'Start time',
          endTime: 'End time',
        },
        cta: 'Build schedule',
        outputTitle: 'Suggested agenda',
      },
      concierge: {
        title: 'Concierge Itinerary',
        description: 'Build a day plan with the right pacing and reservations.',
        labels: {
          city: 'Home city',
          date: 'Date',
          preferences: 'Preferences',
          pace: 'Day pace',
        },
        cta: 'Create itinerary',
        outputTitle: 'Day plan',
      },
      fitness: {
        title: 'Training + Meals',
        description: "Workout splits and meal plans tuned to Fadi's goals.",
        labels: {
          goal: 'Primary goal',
          days: 'Days per week',
          equipment: 'Equipment',
          experience: 'Experience level',
          diet: 'Nutrition style',
        },
        cta: 'Generate fitness plan',
        outputTitle: 'Weekly plan',
      },
      email: {
        title: 'Email Writer',
        description: 'Ready-to-send emails with the right tone.',
        labels: {
          recipient: 'Recipient',
          purpose: 'Email goal',
          tone: 'Tone',
          points: 'Key points',
        },
        cta: 'Create email',
        outputTitle: 'Draft ready',
      },
      analyzer: {
        title: 'Document Analyzer',
        description: 'Executive summary, actions, and open questions at a glance.',
        labels: {
          document: 'Paste the document here',
        },
        cta: 'Analyze document',
        outputTitle: 'Executive summary',
      },
      chat: {
        title: 'Assistant Chat',
        description: "Fast answers with Fadi's context in mind.",
        labels: {
          message: 'Write a message',
          hint: 'Example: create a plan for tomorrow with meetings and training.',
        },
        cta: 'Send',
      },
    },
    contact: {
      title: "Set up Fadi's assistant",
      subtitle:
        'Tell the assistant how Fadi works and it will generate a brief with priorities and next steps.',
      highlights: [
        'Daily schedule + priorities',
        'Training goals + equipment',
        'Nutrition preferences',
        'Home base + frequent travel',
      ],
      form: {
        name: 'Name',
        focus: 'Weekly focus',
        trainingGoal: 'Fitness goal',
        dietaryStyle: 'Nutrition preferences',
        homeCity: 'Home city',
        submit: 'Generate brief',
      },
      result: {
        title: 'Assistant brief',
        nextStepsTitle: 'Recommended next actions',
      },
    },
    bodega: {
      title: 'Bodega Control',
      subtitle: 'Restaurant inventory system for Chile. Track stock, expirations, and losses in real time.',
      eyebrow: 'Loss Prevention',
      views: {
        dashboard: 'Dashboard',
        productos: 'Products',
        movimientos: 'Movements',
        vencimientos: 'Expirations',
        mermas: 'Losses',
        reportes: 'Reports',
      },
      dashboard: {
        totalProducts: 'Registered products',
        totalValue: 'Total inventory value',
        activeAlerts: 'Active alerts',
        monthlyLoss: 'Monthly loss',
        lossTarget: 'Target: under 2% of inventory',
        nearExpiry: 'Expiring soon (7 days)',
        lowStock: 'Below minimum stock',
        recentMovements: 'Recent movements',
        lossBreakdown: 'Losses by category',
        currency: 'CLP',
      },
      products: {
        addProduct: 'Add product',
        name: 'Name',
        sku: 'SKU',
        category: 'Category',
        unit: 'Unit',
        zone: 'Storage zone',
        minStock: 'Min stock',
        maxStock: 'Max stock',
        currentStock: 'Current stock',
        cost: 'Unit cost (CLP)',
        supplier: 'Supplier',
        shelfLife: 'Shelf life (days)',
        save: 'Save',
        cancel: 'Cancel',
        search: 'Search product...',
      },
      movements: {
        addMovement: 'Record movement',
        product: 'Product',
        type: 'Type',
        quantity: 'Quantity',
        responsable: 'Responsible',
        notes: 'Notes',
        date: 'Date',
        types: {
          entrada: 'Incoming',
          salida: 'Outgoing',
          ajuste: 'Adjustment',
          merma: 'Loss',
        },
      },
      expiry: {
        title: 'Expiration Control',
        expired: 'Expired',
        critical: 'Expires today or tomorrow',
        warning: 'Expires in 7 days',
        ok: 'Valid',
        daysLeft: 'days left',
        lot: 'Lot',
        noExpiry: 'No products expiring soon',
      },
      losses: {
        addLoss: 'Record loss',
        reason: 'Reason',
        costImpact: 'Cost impact (CLP)',
        preventable: 'Preventable',
        yes: 'Yes',
        no: 'No',
        reasons: {
          vencimiento: 'Expiration',
          deterioro: 'Deterioration',
          robo: 'Theft',
          error_conteo: 'Count error',
          mal_almacenamiento: 'Poor storage',
          devolucion_proveedor: 'Supplier return',
          otro: 'Other',
        },
        totalLoss: 'Total loss for period',
        preventableRate: 'Preventable rate',
      },
      reports: {
        title: 'Reports & Analytics',
        lossVsInventory: 'Loss vs. Inventory',
        lossByReason: 'Losses by reason',
        lossByCategory: 'Losses by category',
        stockTurnover: 'Stock turnover',
        topLosses: 'Top loss products',
        recommendations: 'Recommendations',
      },
      categories: {
        carnes: 'Meats',
        pescados: 'Seafood',
        lacteos: 'Dairy',
        verduras: 'Vegetables',
        frutas: 'Fruits',
        abarrotes: 'Dry goods',
        bebidas: 'Beverages',
        congelados: 'Frozen',
        condimentos: 'Seasonings',
        limpieza: 'Cleaning',
      },
      zones: {
        refrigerado: 'Refrigerated (0-5°C)',
        congelado: 'Frozen (-18°C)',
        seco: 'Dry storage',
        ambiente: 'Room temperature',
      },
      units: ['kg', 'lt', 'unit', 'box', 'bag', 'bottle'],
      alerts: {
        lowStock: 'below minimum stock',
        nearExpiry: 'expiring soon',
        expired: 'expired',
        highLoss: 'high loss detected',
      },
    },
  },
};
