import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Broker, Load } from "@prisma/client";

export async function generateInvoicePdf(load: Load, broker: Broker) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const { height } = page.getSize();

  page.drawText("Invoice Packet", {
    x: 50,
    y: height - 60,
    size: 20,
    font,
    color: rgb(0.1, 0.1, 0.1),
  });

  const lines = [
    `Broker: ${broker.name}`,
    `Load Number: ${load.loadNumber}`,
    `Broker Reference: ${load.brokerRef}`,
    `Pickup Date: ${load.pickupDate ? load.pickupDate.toDateString() : "N/A"}`,
    `Delivery Date: ${load.deliveryDate ? load.deliveryDate.toDateString() : "N/A"}`,
    `Amount: ${load.amount ? `$${load.amount.toFixed(2)}` : "Pending"}`,
  ];

  let y = height - 110;
  for (const line of lines) {
    page.drawText(line, {
      x: 50,
      y,
      size: 12,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });
    y -= 24;
  }

  page.drawText("Generated by POD-to-Pay Autopilot", {
    x: 50,
    y: 60,
    size: 10,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  return pdfDoc.save();
}
